"""Initial database schema with CV models and embeddings

Revision ID: 4dfd12cfc866
Revises: 
Create Date: 2025-08-12 17:37:24.378201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4dfd12cfc866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_email_hash'), 'candidate', ['email_hash'], unique=False)
    op.create_index(op.f('ix_candidate_name_hash'), 'candidate', ['name_hash'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('certificationembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('certification_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificationembedding_resume_id'), 'certificationembedding', ['resume_id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumeembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumeembedding_resume_id'), 'resumeembedding', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resumeembedding_section_type'), 'resumeembedding', ['section_type'], unique=False)
    op.create_table('resumeskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumeskill')
    op.drop_index(op.f('ix_resumeembedding_section_type'), table_name='resumeembedding')
    op.drop_index(op.f('ix_resumeembedding_resume_id'), table_name='resumeembedding')
    op.drop_table('resumeembedding')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_index(op.f('ix_certificationembedding_resume_id'), table_name='certificationembedding')
    op.drop_table('certificationembedding')
    op.drop_table('resume')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_candidate_name_hash'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_email_hash'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
